In [2]:
import pandas as pd

In [4]:
tickets = pd.read_csv('data_safe_copy.csv')
tickets.shape

(500, 5)

In [5]:
tickets.head()

  ticket_id         opened_at   category priority resolution_minutes
0   TK-0001  2024-03-01 09:00    billing      low                 45
1   TK-0002  2024-03-01 09:30    account   medium                 30
2   TK-0003  2024-03-01 10:00  technical     high                 75
3   TK-0004  2024-03-01 10:30    billing      low                NaN
4   TK-0005  2024-03-01 11:00    account   medium            unknown

In [6]:
tickets.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ticket_id           500 non-null    str
 1   opened_at           500 non-null    str
 2   category            500 non-null    str
 3   priority            500 non-null    str
 4   resolution_minutes  450 non-null    str
dtypes: str(5)
memory usage: 19.7 KB

In [10]:
tickets['opened_at'] = pd.to_datetime(tickets['opened_at'], errors='coerce')
tickets[['category', 'priority']] = (tickets[['category', 'priority']].apply(lambda col: col.str.strip().str.lower()))

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ticket_id           500 non-null    str
 1   opened_at           500 non-null    datetime64[us]
 2   category            500 non-null    str
 3   priority            500 non-null    str
 4   resolution_minutes  450 non-null    str
dtypes: datetime64[us](1), str(4)
memory usage: 19.7 KB

In [14]:
print(tickets['category'].unique())
print(tickets['priority'].unique())

<StringArray>
['billing', 'account', 'technical']
Length: 3, dtype: str
<StringArray>
['low', 'medium', 'high']
Length: 3, dtype: str

In [16]:
tickets["resolution_minutes"] = pd.to_numeric(tickets["resolution_minutes"],errors="coerce")
tickets.head()

  ticket_id           opened_at   category priority  resolution_minutes
0   TK-0001 2024-03-01 09:00:00    billing      low                45.0
1   TK-0002 2024-03-01 09:30:00    account   medium                30.0
2   TK-0003 2024-03-01 10:00:00  technical     high                75.0
3   TK-0004 2024-03-01 10:30:00    billing      low                 NaN
4   TK-0005 2024-03-01 11:00:00    account   medium                 NaN

In [18]:
missing_count = tickets['resolution_minutes'].isna().sum()
print(missing_count)

100

In [20]:
tickets_clean = tickets.dropna(subset=['resolution_minutes'])

print("Before cleaning:", len(tickets))
print("After cleaning:", len(tickets_clean))

Before cleaning: 500
After cleaning: 400

In [21]:
(tickets['resolution_minutes']>=0).all()

np.False_

In [22]:
print("Categories:", tickets_clean["category"].unique())
print("Priorities:", tickets_clean["priority"].unique())

Categories: <StringArray>
['billing', 'account', 'technical']
Length: 3, dtype: str
Priorities: <StringArray>
['low', 'medium', 'high']
Length: 3, dtype: str

In [28]:
total_records = len(tickets)
clean_records = len(tickets_clean)
missing_resolution = tickets["resolution_minutes"].isna().sum()
avg_resolution = tickets_clean["resolution_minutes"].mean()
max_resolution = tickets_clean["resolution_minutes"].max()


summary = {
    "total_records": total_records,
    "clean_records": clean_records,
    "missing_resolution": missing_resolution,
    "avg_resolution": avg_resolution,
    "max_resolution": max_resolution
}

for k,v in summary.items():
    print(k,':',v)

total_records : 500
clean_records : 400
missing_resolution : 100
avg_resolution : 57.5
max_resolution : 120.0

In [29]:
print(
    "Check:",
    clean_records + missing_resolution == total_records
)

Check: True

{'avg_resolution': np.float64(57.5),
 'clean_records': 400,
 'max_resolution': np.float64(120.0),
 'missing_resolution': np.int64(100),
 'total_records': 500}